### ISSUE TITLE
Typo: l3duild -> l3build

### ISSUE THREAD

**Issue by muzimuzhi** [zongpingding/zongpingding.github.io#1]
The title of https://www.zpding.tech/2024/09/16/l3build_Note/ reads "l3duild introduction", in which the "l3duild" should be "l3build".

**Comment by zongpingding** [comment]
> The title of https://www.zpding.tech/2024/09/16/l3build_Note/ reads "l3duild introduction", in which the "l3duild" should be "l3build". 

@muzimuzhi Already fixed it, thanks for pointing out.

**Comment by muzimuzhi** [comment]
Fixed in f6686bfc6091938b08721f63c567455f1c2bc24f.
